notifications:
  email:
    - eric.crawford@mail.mcgill.ca

language: python
python:
  - 3.5

os: linux
dist: trusty
sudo: false

branches:
  only:
    - master

git:
  depth: 3

cache:
  apt: true

before_install:
  - sh travis-setup.sh

install:
  - pip install -e .

script:
  - py.test